# Generated by Django 3.1.6 on 2021-02-26 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomvoyage', models.CharField(max_length=100, null=True)),
                ('duree', models.IntegerField(null=True)),
                ('photo', models.ImageField(upload_to='pics')),
                ('prix', models.FloatField(null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destination.destination')),
            ],
        ),
    ]
