# Generated by Django 3.1.6 on 2021-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='origine',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
