# Generated by Django 3.1.6 on 2021-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_voyage_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='depart',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='retour',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
