# Generated by Django 3.1.6 on 2021-03-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_voyage_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='retour',
        ),
    ]
