# Generated by Django 3.1.6 on 2021-03-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_auto_20210301_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='origine',
        ),
    ]
