# Generated by Django 3.1.6 on 2021-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_voyage_classe'),
        ('excursion', '0002_excursion_photoexcursion'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='voyage',
            field=models.ManyToManyField(to='voyage.Voyage'),
        ),
    ]
